# Generated by Django 2.2.16 on 2022-02-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220202_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
